#! /bin/sh

# startup
sxhkd &
nitrogen --restore
picom --experimental-backends -b &
$HOME/.config/polybar/launch.sh --forest &

bspc config border_width         2
bspc config window_gap          16 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding          20
bspc config bottom_padding       10
bspc config left_padding         20
bspc config right_padding 	     20

bspc monitor -d 1 2 3 4 5

bspc rule -a vlc desktop='^5' state=fullscreen
bspc rule -a firefox desktop='^2' state=tiled
bspc rule -a Emacs desktop='^3' state=tiled
bspc rule -a JDownloader2 desktop='^4' state=tiled
bspc rule -a Evolution desktop='^4' state=tiled

